### PR TITLE
Drop missing input values from the initial input keypoints.

### PR DESCRIPTION
**Pull request by si-you**

### CODE REVIEW

**Comment by mmilanifard** [comment]
Missing values are the only reasonable values that might need removing from the input values. Why not just pass missing values map to the initializer? The code is already somewhat confusing, so I'd rather not add a new concept.

**Comment by mmilanifard** [comment]
Once again, thanks for the contribution.

**Comment by si-you** [comment]
Sure. I updated code so please take a look :).

**Comment by mmilanifard** [comment]
Thanks for the update. Might take a bit to merge internally and here.

**Pull request merged**
